### ISSUE TITLE
Support mermaid flowchart

### ISSUE THREAD

**Issue by ecattez** [Candy-Doc/candy-doc-maven-plugin#123]
## Description

**Is your feature request related to a problem? Please describe.**
The plugin does not offer a simple way to visualize bounded contexts as graphs.

**Describe the solution you'd like**
I'd like an implementation of mermaid flowchart. It will unlock the possibilities to create bounded context graphs that could be stored inside markdown files such as README.md.

**Describe alternatives you've considered**
None.

**Additional context**

Github support: [A clear and concise description of what you want to happen.](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams)

Flowchart syntax: https://mermaid-js.github.io/mermaid/#/./flowchart?id=flowcharts-basic-syntax

**Comment by Yugo-Cartron** [comment]
This feature is being implemented. However, it uses cytoscape.js instead of mermaid
