### ISSUE TITLE
CanonicalName value is marked non-null but is null

### ISSUE THREAD

**Issue by AudranL** [Candy-Doc/candy-doc-maven-plugin#187]
## Description

**Describe the bug**
The goal ubiquitous-language fails when I run it on my project with a message "value is marked non-null but is null".

**To Reproduce**
1. Run the goal ubiquitous-language on a project

## Version
2.0.1

## Extra info

**Screenshots**
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/91188510/231144558-3476234e-bdbe-461c-8eaa-dd1ad9f8a0b7.png">

**Desktop (please complete the following information):**
- OS: Mac OS 13.3.1

**Comment by ecattez** [comment]
>  Building code that universally gets the class name of an object can have some unexpected pitfalls in Java. You should never rely on class.getSimpleName() or class.getCanonicalName() to give you anything meaningful if your code could be passed arbitrary objects of any class. Especially for anonymously created objects, they will be empty or null.

From this link: https://coderwall.com/p/lap9ww/don-t-rely-on-class-getsimplename-or-class-getcanonicalname.

It might be due to anonymous objects (enum with abstract methods, inner classes, lambdas, ...)
